### ISSUE TITLE
Question on dataset format

### ISSUE THREAD

**Issue by esmab** [XuhuiZhou/Toxic_Debias#2]
Hi Xuhui,

Thanks for making your code public! I would love to use your implementation for the ensemble model for further research, however I cannot get either the regular model or the debiased ensemble model to run on the Founta dataset. toxic.py seems to have some filenames hardcoded in it (e.g. 'ND_founta_trn_dial_pAPI.csv'). Even when I change these, I'm getting KeyError when processing the examples.  Would you be able to provide more details on the format, labels etc. that run_toxic.sh and run_toxic_debias.sh expects as data? Thanks in advance!

**Comment by XuhuiZhou** [comment]
Hi, You can find a complete list of entries of data that we need for experiments in `data/demo.csv`. If you want the original dataset, feel free to email me about this. (Since we are not the author of the dataset, we are not sure whether we can publicly share it.)

**Comment by esmab** [comment]
Oh, sorry I didn't see that you included a demo.csv, that solves my issue. Thanks!
